### ISSUE TITLE
"HELTEC_BOARD was not declared in this scope" - LoRaSender.ino

### ISSUE THREAD

**Issue by Frosty-STI** [HelTecAutomation/Heltec_ESP32#132]
I receive these errors upon compiling LoRaSender.ino: 

C:\Users\brend\OneDrive\Documents\Arduino\LoRaReceiver\LoRaReceiver.ino: In function 'void setup()':
C:\Users\brend\OneDrive\Documents\Arduino\LoRaReceiver\LoRaReceiver.ino:57:15: error: 'HELTEC_BOARD' was not declared in this scope
     Mcu.begin(HELTEC_BOARD,SLOW_CLK_TPYE);
               ^~~~~~~~~~~~
C:\Users\brend\OneDrive\Documents\Arduino\LoRaReceiver\LoRaReceiver.ino:57:28: error: 'SLOW_CLK_TPYE' was not declared in this scope
     Mcu.begin(HELTEC_BOARD,SLOW_CLK_TPYE);
                            ^~~~~~~~~~~~~

exit status 1

Compilation error: 'HELTEC_BOARD' was not declared in this scope

Board:
Heltec ESP32 Wireless Stick V3 

I have installed the Heltec_ESP32 library, added the board URL to the board manager ( https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series.git ), and selected 'Heltec Wireless Stick' as my target device.

**Comment by GM-BLUE13** [comment]
I have the same issue. Did you find something?

**Comment by Mr-HaleYa** [comment]
You added `https://resource.heltec.cn/download/package_heltec_esp32_index.json` to your board manager, restarted Arduino, and installed the board and it looks like this?
![image](https://github.com/HelTecAutomation/Heltec_ESP32/assets/42821995/8203a505-7bff-4042-8561-0dd6fc68cc22)

I had that error when I had the old board framework still installed

**Comment by Frosty-STI** [comment]
Thank you @Mr-HaleYa !!!!!!!!!!! Works perfect now. I wasn't sure if I had the right board manager URL but the one you provided definitely is, thanks again :)
