### ISSUE TITLE
Add support for heltec_wifi_lora_32_V3

### ISSUE THREAD

**Issue by jaecktec** [HelTecAutomation/Heltec_ESP32#92]
I recently bought a lora 32 and got a [wifi-lora-32-v3](https://heltec.org/project/wifi-lora-32-v3/) module. 
However I can't find any examples / included code. 

Can you please release the v3 code?

**Comment by Baptou88** [comment]
I would also be interested to know if there are any code differences between V2 and V3

**Comment by jaecktec** [comment]
I got it to work with the arduino examples, sadly not platformio. 
There are major differences, beginning with a different esp32 being used (esp32-s3 being used), it also has a different pinout

**Comment by Baptou88** [comment]
@jaecktec https://github.com/platformio/platform-espressif32/issues/946
